const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
require('dotenv').config();
const authRoutes = require('./routes/auth');
const paymentRoutes = require('./routes/payment');
const puzzleRoutes = require('./routes/puzzle');
const zkPuzzleRoutes = require('./routes/zkpuzzle');
const metaPuzzleRoutes = require('./routes/metapuzzle');
const app = express();
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'unsafe-inline'"]}}));
app.use(cors({origin:process.env.ALLOWED_ORIGINS?.split(',')||'http://localhost:3000',credentials:true,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','x-request-signature','x-request-timestamp','x-request-nonce']}));
app.use(express.json({limit:'10kb'}));
app.use(express.urlencoded({extended:true,limit:'10kb'}));
app.use(rateLimit({windowMs:15*60*1000,max:100,message:{error:'Too many requests'}}));
app.use((req,res,next)=>{res.setHeader('X-Frame-Options','DENY');res.setHeader('X-Content-Type-Options','nosniff');next();});
app.get('/admin.php',(req,res)=>{console.log('HONEYPOT:',req.ip);res.status(404).send('Not found');});
app.get('/wp-admin',(req,res)=>{console.log('HONEYPOT:',req.ip);res.status(404).send('Not found');});
app.use('/api/auth',authRoutes);
app.use('/api/payment',paymentRoutes);
app.use('/api/puzzle',puzzleRoutes);
app.use('/api/zkpuzzle',zkPuzzleRoutes);
app.use('/api/metapuzzle',metaPuzzleRoutes);
app.get('/health',(req,res)=>res.json({status:'ok',timestamp:new Date().toISOString()}));
app.use((req,res)=>res.status(404).json({error:'Not found'}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:process.env.NODE_ENV==='production'?'Error':err.message});});
const PORT=process.env.PORT||3000;
const MONGODB_URI=process.env.MONGODB_URI||'mongodb://localhost:27017/puzzle-game';
mongoose.connect(MONGODB_URI,{useNewUrlParser:true,useUnifiedTopology:true,maxPoolSize:10}).then(async()=>{console.log('✅ MongoDB');try{const ZKPuzzle=require('./models/ZKPuzzle');await ZKPuzzle.initializePuzzles();}catch(e){}try{const MetaPuzzle=require('./models/MetaPuzzle');await MetaPuzzle.initializePuzzles();}catch(e){}app.listen(PORT,()=>console.log('🚀 MRABT: The Lost Block - Port',PORT));}).catch(e=>{console.error(e);process.exit(1);});
module.exports=app;